version: '3'


services:
   dbos:
     image: mysql:5.7
     volumes:
       - mysql_storage:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: varanasi
       MYSQL_USER: roshan
       MYSQL_PASSWORD: joomla  
       MYSQL_DATABASE: joomladb
       
   joomlaos:
      image: joomla:3.9-php7.2-apache 
      restart: always
      depends_on:
        - dbos
      ports:
        - 8081:80
      environment:
        JOOMLA_DB_HOST: dbos:9999   
        JOOMLA_DB_: roshan
        JOOMLA_DB_PASSWORD: joomla
        JOOMLA_DB_NAME: joomladb
      volumes:
        - joomla_storage:/var/www/html




volumes:
   mysql_storage:
   joomla_storage:
                          